[pse]
server

[pse:vars]
ansible_host={{ lookup('env', 'PSE_HOST', default=undefined()) }}
ansible_port={{ lookup('env', 'PSE_PORT', default='22') }}
ansible_user=root
pse_user={{ lookup('env', 'PSE_USER', default=undefined()) }}
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args=-o StrictHostKeyChecking=accept-new
ansible_ssh_password_mechanism=sshpass